# encoding:UTF-8
from enum import Enum

class InstClass(Enum):
    BASK = 'BASK'
    BNDINDX_FT = 'BNDINDX_FT'
    BOND = 'BOND'
    BOND_FT = 'BOND_FT'
    CCY = 'CCY'
    CD_SW = 'CD_SW'
    CDS_INDX = 'CDS_INDX'
    CFD = 'CFD'
    CFD_OLD = 'CFD_OLD'
    CIS = 'CIS'
    CMDINDX_FT = 'CMDINDX_FT'
    CMDINDX_OP = 'CMDINDX_OP'
    CMDTY = 'CMDTY'
    CMDTY_FT = 'CMDTY_FT'
    CMDTY_FWRD = 'CMDTY_FWRD'
    CMDTY_OP = 'CMDTY_OP'
    CONVBND = 'CONVBND'
    CONVPRF = 'CONVPRF'
    DR = 'DR'
    EQ_SW = 'EQ_SW'
    EQINDX_FT = 'EQINDX_FT'
    EQINDX_OP = 'EQINDX_OP'
    EQINDX_OP2 = 'EQINDX_OP2'
    EQINDX_SW = 'EQINDX_SW'
    EQTY_FT = 'EQTY_FT'
    EQTY_OP = 'EQTY_OP'
    FFA = 'FFA'
    FNCG = 'FNCG'
    FRN = 'FRN'
    FWRD_FX = 'FWRD_FX'
    FX_FT = 'FX_FT'
    FX_OP = 'FX_OP'
    GOVT = 'GOVT'
    INDX = 'INDX'
    IR_FT = 'IR_FT'
    LN_CASH = 'LN_CASH'
    MISC = 'MISC'
    OP_BONDFT = 'OP_BONDFT'
    OP_CMDTY_FT = 'OP_CMDTY_FT'
    ORD = 'ORD'
    PFRD = 'PFRD'
    RIGHTS = 'RIGHTS'
    WRNT = 'WRNT'
